### ISSUE TITLE
Merge upstream

### ISSUE THREAD

**Issue by Fuco1** [mutbuerger/smartparens-ess#1]
Hi, would you be interested in getting this upstream?  I would like to have as much as possible included in the main repo so things are discoverable and up-to-date with the core.

Ideally, I would give you push rights and you would maintain this extension there.  What do you think?

**Comment by mutbuerger** [comment]
Hi! 
First of all, thanks for smartparens! Only recently I decided to work on smartparens-ess again, so that's perfect timing I guess. I'm also okay with maintaining!
